apiVersion: v1
kind: Service

metadata:
  name: monitoring-demo
  namespace: monitoring

  labels:
    app: monitoring-demo

spec:
  selector:
    app: monitoring-demo

  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP

  type: LoadBalancer